### ISSUE TITLE
php parse error

### ISSUE THREAD

**Issue by igregma** [cbdevnet/ipmagnet#1]
Hi,

I got this error:
    mod_fcgid: stderr: PHP Parse error:  syntax error, unexpected 'version' (T_STRING) in index.php on line 114

and changed the line to this here:
     echo '<?xml version="1.1" encoding="UTF-8" ?>';

**Comment by cbdevnet** [comment]
Hi,
you're right, that fixes this occurrence.
The root cause of this is PHP's short_open_tag directive, configurable in php.ini.
Set it to 'off' and it should work as released :)
I'll consider fixing this upstream as multiple reports have come in regarding this.

Thanks,
cbdev

**Comment by cbdevnet** [comment]
Fixed by merged pull request 7f96603
