### ISSUE TITLE
Should tracking link download complete?

### ISSUE THREAD

**Issue by ghost** [cbdevnet/ipmagnet#13]
I've added "ipMagnet Tracking Link" torrent to my torrent client — should the download ever complete?

**Comment by cbdevnet** [comment]
Hi there, and thanks for the question!

As the info-hash (the identifying piece of information between the BitTorrent client and ipMagnet) is randomly generated, it does not identify an actual file to be downloaded. In theory, this could be implemented, but would provide no benefits (and actually defeat the purpose).

As long as the file is being kept incomplete, the client repeatedly asks the Tracker (ipMagnet) for other people to download the file from - this allows us to update the address that sends the requests.
You can watch the "Tracker info" column in your client (if it provides any), the address your client presents to the outside world should be shown there, too, in addition to the web interface.

Hope that helps clear it up :)
