### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by zero77** [cbdevnet/ipmagnet#14]
Can you please add a login page or another form of security for when ipmagnet is being accessed remotely and not from localhost.
Thanks

**Comment by cbdevnet** [comment]
Hi there! You can usually configure that in your web server (look for a section on 'basic authentication') in the documentation.

Adding authentication to ipMagnet itself would be a bigger change (and one I'd like to avoid if possible), as it would

* Require an additional dialog/page for login
* Require additional interfaces for user management
* Require additional database handling and functionality for user/password storage
* Increase attack surface (can't attack passwords that don't exist)

It would also (in my opinion) bring very little benefits in comparison to the effort it would take (the worst an attacker could gain is a mapping of past IP addresses to more-or-less current ones), and even that is hard as the attacker would have to guess the randomly generated hash of other users.

Of course, users should not rely on having the same magnet link in their client for a long time, but rather periodically generate new ones and use the 'Clear my data' button.

If you can tell me what web server you're using, I might be able to find you some example on configuring authentication for it :)

**Comment by zero77** [comment]
Hi 
Thanks for the reply, you make some good points, I agree that this could end up creating more of an attack surface, which should be avoided.

Although, I am looking for as simple a solution as possible that won’t complicate things essentially, I am trying to stop unauthorised users or attackers gaining access to the ipmagnet interface.

Because, I am running ipmagnet on a headerless apache server and cannot access the interface from localhost.

**Comment by cbdevnet** [comment]
Hm another problem I see with this is that the BitTorrent clients accessing the tracking link need to provide the password, too - I'm not entirely sure how advanced their HTTP client implementations are (most probably use libcurl or something similar) and whether they support credentials passed within the URL (I think libcurl does, though).

To introduce a (really simple) access control, you can insert the following lines into index.php (at/after line 60)

```
if (!isset($_SERVER["PHP_AUTH_USER"]) || $_SERVER["PHP_AUTH_PW"] != "SUPER_SECRET_PASSWORD") {
    header('WWW-Authenticate: Basic realm="ipMagnet"');
    header('HTTP/1.0 401 Unauthorized');
    exit();
} 
```

Replace `SUPER_SECRET_PASSWORD` with a plaintext password of your choice. This should allow BitTorrent clients to access the tracking link without problems while preventing access to the web panel.

**Comment by zero77** [comment]
@cbdevnet 
Thanks, that seems to be working well, is it worth adding to the readme.

**Comment by cbdevnet** [comment]
Thanks for the suggestion, just added it :)
