### ISSUE TITLE
Importance of trailing slash for $TRACKER

### ISSUE THREAD

**Issue by jamesmacwhite** [cbdevnet/ipmagnet#4]
I don't know if its worth highlighting the importance of the trailing forward slash that must follow after the port number for the `$TRACKER` variable. In general web URL terms this would not be common, but in the case of ipMagnet you must have the trailing slash, otherwise you'll get "Too many redirects" or something similar in the tracker response.

**Comment by cbdevnet** [comment]
You're right, that should be mentioned - I'll add a comment :)
Thanks for your work!
